### PR TITLE
Add validators

### PR DESCRIPTION
**Pull request by jhirbour**
Add JSON schema validation for all the things

### CODE REVIEW

**Comment by treznick** [comment]
@danbernier :eyes: ?

**Comment by danbernier** [comment]
I think this is a very good direction to move in. My comments are all minor, and can be addressed later, if the need arises. :shipit:

**Comment by treznick** [comment]
there's a bug here if you gem install this branch - the validators can't find the schema files.

**Comment by danbernier** [comment]
I see that the schema files aren't included in the .gemspec - that's probably why.

**Comment by treznick** [comment]
I'm pushing a fix that uses `File.dirname(__FILE__) + '/../schemas/<schema name>'`. Should I use the gemspec?

**Pull request merged**
